### ISSUE TITLE
Simple client example

### ISSUE THREAD

**Issue by karampok** [vmware/go-vmware-nsxt#15]
Greetings,
is there any small example how can I use this library? 
It is unclear how to properly set up the client with the correct configuration /authentication.

Thanks!

**Comment by annakhm** [comment]
Hi @karampok, @rowanjacobs - indeed terraform provider is a good example. I will include it in the documentation, thanks for bringing it into attention!

**Comment by karampok** [comment]
Thx! this looks like start!
