### ISSUE TITLE
NewAPIClient panic

### ISSUE THREAD

**Issue by pvorontsovd** [vmware/go-vmware-nsxt#29]
will be panic here
https://github.com/vmware/go-vmware-nsxt/blob/master/api_client.go#L373

rand.Intn panic if argument <= 0
in argument we pass config.RetryMinDelay, whose value 0 by default

**Comment by annakhm** [comment]
Thank you @pvorontsovd, fixed with https://github.com/vmware/go-vmware-nsxt/pull/30
